<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>practica_estadistica</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="practica_estadistica_files/libs/clipboard/clipboard.min.js"></script>
<script src="practica_estadistica_files/libs/quarto-html/quarto.js"></script>
<script src="practica_estadistica_files/libs/quarto-html/popper.min.js"></script>
<script src="practica_estadistica_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="practica_estadistica_files/libs/quarto-html/anchor.min.js"></script>
<link href="practica_estadistica_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="practica_estadistica_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="practica_estadistica_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="practica_estadistica_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="practica_estadistica_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">



<section id="practica-pedro-dominguez" class="level1">
<h1>PRACTICA PEDRO DOMINGUEZ</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Cargar los datos en un dataframe llamado: airbnb</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>airbnb<span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">'data//airbnb.csv'</span>,<span class="at">sep =</span> <span class="st">','</span>, <span class="at">stringsAsFactors =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Mostrar las primeras 6 filas del dataframe</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>airbnb[<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Zipcode Neighbourhood.Cleansed Property.Type       Room.Type Accommodates
1   28004            Universidad     Apartment    Private room            2
2   28004            Universidad     Apartment Entire home/apt            6
3   28004            Universidad     Apartment Entire home/apt            3
4   28004            Universidad          Loft Entire home/apt            3
5   28015            Universidad     Apartment Entire home/apt            5
6   28004            Universidad     Apartment Entire home/apt            2
  Bathrooms Bedrooms Beds Bed.Type
1         2        1    1 Real Bed
2         1        3    5 Real Bed
3         1        2    2 Real Bed
4         2        1    1 Real Bed
5         1        1    1 Real Bed
6         1        0    1 Real Bed
                                                                                                                                                                                                                                                                                                                                                         Amenities
1                                                                                                                                                                              TV,Wireless Internet,Kitchen,Pets allowed,Pets live on this property,Buzzer/wireless intercom,Heating,Suitable for events,Washer,First aid kit,Essentials,Lock on bedroom door,Iron
2                                                                                                                                                                                      TV,Internet,Wireless Internet,Air conditioning,Kitchen,Indoor fireplace,Heating,Family/kid friendly,Washer,Dryer,Smoke detector,Carbon monoxide detector,Essentials,Shampoo
3                                                                                                                                                                                           TV,Internet,Wireless Internet,Air conditioning,Kitchen,Doorman,Heating,Family/kid friendly,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace
4                                           TV,Internet,Wireless Internet,Air conditioning,Kitchen,Pets allowed,Breakfast,Elevator in building,Indoor fireplace,Buzzer/wireless intercom,Heating,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace,translation missing: en.hosting_amenity_49,translation missing: en.hosting_amenity_50
5                                                                                                                                                                                                               TV,Wireless Internet,Air conditioning,Kitchen,Smoking allowed,Pets allowed,Elevator in building,Heating,Family/kid friendly,Washer,Essentials,Iron
6 TV,Cable TV,Internet,Wireless Internet,Air conditioning,Wheelchair accessible,Kitchen,Doorman,Elevator in building,Buzzer/wireless intercom,Heating,Washer,Smoke detector,Carbon monoxide detector,First aid kit,Safety card,Fire extinguisher,Essentials,Shampoo,24-hour check-in,Hangers,Hair dryer,Iron,Laptop friendly workspace,Self Check-In,Doorman Entry
  Square.Feet Price Review.Scores.Rating
1          NA    35                   NA
2          NA    92                   96
3          NA    55                   91
4          NA    60                  100
5         538    75                   90
6          NA    55                   95</code></pre>
</div>
</div>
<p>Renombrar las columnas de la siguiente forma:</p>
<table class="table">
<thead>
<tr class="header">
<th>Nombre original</th>
<th>Nuevo nombre</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Zipcode</td>
<td>CodigoPostal</td>
</tr>
<tr class="even">
<td>Neighbourhood.Cleansed</td>
<td>Barrio</td>
</tr>
<tr class="odd">
<td>Property.Type</td>
<td>TipoPropiedad</td>
</tr>
<tr class="even">
<td>Room.Type</td>
<td>TipoAlquiler</td>
</tr>
<tr class="odd">
<td>Accommodates</td>
<td>MaxOcupantes</td>
</tr>
<tr class="even">
<td>Bathrooms</td>
<td>NumBanyos</td>
</tr>
<tr class="odd">
<td>Bedrooms</td>
<td>NumDormitorios</td>
</tr>
<tr class="even">
<td>Beds</td>
<td>NumCamas</td>
</tr>
<tr class="odd">
<td>Bed.Type</td>
<td>TipoCama</td>
</tr>
<tr class="even">
<td>Amenities</td>
<td>Comodidades</td>
</tr>
<tr class="odd">
<td>Square.Feet</td>
<td>PiesCuadrados</td>
</tr>
<tr class="even">
<td>Price</td>
<td>Precio</td>
</tr>
<tr class="odd">
<td>Review.Scores.Rating</td>
<td>Puntuacion</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(airbnb)<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"CodigoPostal"</span>,<span class="st">"Barrio"</span>,<span class="st">"TipoPropiedad"</span>,<span class="st">"TipoAlquiler"</span>,<span class="st">"MaxOcupantes"</span>,<span class="st">"NumBanyos"</span>,</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="st">"NumDormitorios"</span>,<span class="st">"NumCamas"</span>,<span class="st">"TipoCama"</span>,<span class="st">"Comodidades"</span>,<span class="st">"PiesCuadrados"</span>,<span class="st">"Precio"</span>,<span class="st">"Puntuacion"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Crea una nueva columna llamada MetrosCuadrados a partir de la columna PiesCuadrados.</p>
<p>Ayuda: 1 pie cuadrado son 0,092903 metros cuadrdados</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>MetrosCuadrados <span class="ot">&lt;-</span> airbnb<span class="sc">$</span>PiesCuadrados<span class="sc">*</span><span class="fl">0.092903</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Miremos el código postal. Es una variable con entradas erroneas. Hay valores como ’‘,’-’ y ‘28’ que deberían ser considerados como NA. Así mismo también debería ser NA todos los que no compiencen por 28, ya que estamos con códigos postales de Madrid</p>
<p>El código postal 28002, 28004 y 28051 tienen entradas repetidas. Por ejemplo las entradas 28002 deberían ir dnetro de 28002</p>
<p>El codigo 2804 debería ser 28004, 2805 deberia ser 28005 y 2815 juncto con 2815 debería ser 28015</p>
<p>Limpia los datos de la columna Codigo Postal</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#limpieza_1 `` '-' y '28' son NA</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>limpieza_1 <span class="ot">&lt;-</span> <span class="fu">which</span>((airbnb<span class="sc">$</span>CodigoPostal <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">''</span>,<span class="st">'-'</span>,<span class="st">'28'</span>)) )</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>airbnb[limpieza_1,<span class="st">'CodigoPostal'</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#limpieza 2 NA todos los que no compiencen por 28</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>limpieza_2 <span class="ot">&lt;-</span> <span class="fu">which</span>(<span class="sc">!</span>(<span class="fu">substring</span>(airbnb<span class="sc">$</span>CodigoPostal,<span class="dv">1</span>,<span class="dv">2</span>) <span class="sc">==</span> <span class="st">'28'</span>) )</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>airbnb[limpieza_2,<span class="st">'CodigoPostal'</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#limpieza 3 todo lo contenga 28002 debe ser solo 28002</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>limpieza_3 <span class="ot">&lt;-</span> <span class="fu">which</span>(<span class="fu">grepl</span>(<span class="st">'28002'</span>,airbnb<span class="sc">$</span>CodigoPostal))</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>airbnb[limpieza_3,<span class="st">'CodigoPostal'</span>] <span class="ot">&lt;-</span> <span class="st">'28002'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#limpieza 4 todo lo contenga 28004 debe ser solo 28004</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>limpieza_4 <span class="ot">&lt;-</span> <span class="fu">which</span>(<span class="fu">grepl</span>(<span class="st">'28004'</span>,airbnb<span class="sc">$</span>CodigoPostal))</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>airbnb[limpieza_4,<span class="st">'CodigoPostal'</span>] <span class="ot">&lt;-</span> <span class="st">'28004'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">#limpieza 5 todo lo contenga 28051 debe ser solo 28051</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>limpieza_5 <span class="ot">&lt;-</span> <span class="fu">which</span>(<span class="fu">grepl</span>(<span class="st">'28051'</span>,airbnb<span class="sc">$</span>CodigoPostal))</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>airbnb[limpieza_5,<span class="st">'CodigoPostal'</span>] <span class="ot">&lt;-</span> <span class="st">'28051'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#limpieza 6 El codigo 2804 debería ser 28004</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>limpieza_6 <span class="ot">&lt;-</span> <span class="fu">which</span>(airbnb<span class="sc">$</span>CodigoPostal <span class="sc">==</span> <span class="st">'2804'</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>airbnb[limpieza_6,<span class="st">'CodigoPostal'</span>] <span class="ot">&lt;-</span> <span class="st">'28004'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#limpieza 7  El codigo 2805 debería ser 28005</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>limpieza_7 <span class="ot">&lt;-</span> <span class="fu">which</span>(airbnb<span class="sc">$</span>CodigoPostal <span class="sc">==</span> <span class="st">'2805'</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>airbnb[limpieza_7,<span class="st">'CodigoPostal'</span>] <span class="ot">&lt;-</span> <span class="st">'28005'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#limpieza 8 El codigo 2815 debería ser 28015</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>limpieza_8 <span class="ot">&lt;-</span> <span class="fu">which</span>(airbnb<span class="sc">$</span>CodigoPostal <span class="sc">==</span> <span class="st">'2815'</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>airbnb[limpieza_8,<span class="st">'CodigoPostal'</span>] <span class="ot">&lt;-</span> <span class="st">'28015'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">#limpieza 9 Esta limpieza es adicional ya que se ha observado que existe </span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co"># el codigo 280013 que deberia de ser el 28013</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>limpieza_9 <span class="ot">&lt;-</span> <span class="fu">which</span>(airbnb<span class="sc">$</span>CodigoPostal <span class="sc">==</span> <span class="st">'280013'</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>airbnb[limpieza_9,<span class="st">'CodigoPostal'</span>] <span class="ot">&lt;-</span> <span class="st">'28013'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Una vez limpios los datos ¿Cuales son los códigos postales que tenemos?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>tabla_cp <span class="ot">&lt;-</span> <span class="fu">table</span>(<span class="fu">droplevels</span>(airbnb<span class="sc">$</span>CodigoPostal))</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>tabla_cp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
28001 28002 28003 28004 28005 28006 28007 28008 28009 28010 28011 28012 28013 
  231   171   185  1795  1195   218   206   338   216   384   250  2060  1020 
28014 28015 28016 28017 28018 28019 28020 28021 28022 28023 28024 28025 28026 
  630   601    76   107    43   200   192    58    30    23    44   123    93 
28027 28028 28029 28030 28031 28032 28033 28034 28035 28036 28037 28038 28039 
  122   263   110    73    27    33    89    45    59    67    65    77   160 
28040 28041 28042 28043 28044 28045 28046 28047 28048 28049 28050 28051 28052 
   16    63    90   103    19   495    32    67     1     3    58    17     1 
28053 28054 28055 28056 28058 28060 28094 28105 28850 
   85    12    12     1     1     1     1     1     1 </code></pre>
</div>
</div>
<p>¿Cuales son los 5 códigos postales con más entradas? ¿Y con menos? ¿Cuantas entradas tienen?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>top_5_cp <span class="ot">&lt;-</span> <span class="fu">sort</span>(tabla_cp, <span class="at">decreasing =</span> <span class="cn">TRUE</span>)[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>PD: Top 5 codigos postales y sus numeros de entradas</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>top_5_cp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
28012 28004 28005 28013 28014 
 2060  1795  1195  1020   630 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>bottom_5_cp <span class="ot">&lt;-</span> <span class="fu">sort</span>(tabla_cp, <span class="at">decreasing =</span> <span class="cn">FALSE</span>)[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>PD: Bottom 5 codigos postales y sus numeros de entradas</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>bottom_5_cp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
28048 28052 28056 28058 28060 
    1     1     1     1     1 </code></pre>
</div>
</div>
<p>¿Cuales son los barrios que hay en el código postal 28012?¿Cuantas entradas hay en cada uno de esos barrios para el codigo postal 28012?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>cp_28012 <span class="ot">&lt;-</span> <span class="fu">which</span>(airbnb<span class="sc">$</span>CodigoPostal <span class="sc">==</span> <span class="st">'28012'</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>tabla_cp_28012 <span class="ot">&lt;-</span> <span class="fu">table</span>(<span class="fu">droplevels</span>(airbnb[cp_28012,<span class="st">'Barrio'</span>]))</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>tabla_cp_28012</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
        Acacias        Arapiles          Atocha          Cortes        Delicias 
             13               1               1             216               1 
    Embajadores            Goya         Palacio Palos de Moguer             Sol 
           1449               1              27              46             301 
    Universidad 
              4 </code></pre>
</div>
</div>
<p>¿Cuantos barrios hay en todo el dataset airbnb? ¿Cuales son?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>tabla_barrios <span class="ot">&lt;-</span> <span class="fu">table</span>(<span class="fu">droplevels</span>(airbnb<span class="sc">$</span>Barrio))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>PD: Numero de barrios en el dataset:</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(tabla_barrios)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 125</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>PD: Cuales son los barrios:</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>tabla_barrios</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
                    Abrantes                      Acacias 
                          18                          145 
                     Adelfas                   Aeropuerto 
                          51                            6 
                     Aguilas             Alameda de Osuna 
                          15                           24 
                     Almagro                     Almenara 
                         155                           62 
                 Almendrales                       Aluche 
                          45                           45 
                      Ambroz                      Amposta 
                          12                            5 
            Apostol Santiago                     Arapiles 
                          15                          182 
                     Aravaca                        Arcos 
                          16                           18 
                   Argüelles                       Atocha 
                         264                           18 
               Bellas Vistas                   Berruguete 
                          79                           67 
                  Buenavista                     Butarque 
                          22                            6 
                  Campamento                     Canillas 
                          22                           42 
                  Canillejas                     Cármenes 
                           7                           30 
               Casa de Campo   Casco Histórico de Barajas 
                          75                           28 
 Casco Histórico de Vallecas Casco Histórico de Vicálvaro 
                          40                           20 
                  Castellana                     Castilla 
                          97                           26 
                 Castillejos                      Chopera 
                          81                          112 
               Ciudad Jardín         Ciudad Universitaria 
                          55                           34 
                      Colina                     Comillas 
                          16                           59 
                  Concepción                   Corralejos 
                          46                            5 
                      Cortes                  Costillares 
                         750                           32 
              Cuatro Caminos               Cuatro Vientos 
                         120                            3 
                    Delicias                    El Goloso 
                         126                            3 
                  El Plantío                      El Viso 
                           3                           45 
                 Embajadores                    Entrevías 
                        1844                           13 
                    Estrella                    Fontarrón 
                          28                           24 
            Fuente del Berro                Fuentelareina 
                          68                            3 
                  Gaztambide                         Goya 
                         142                          229 
                  Guindalera                       Hellín 
                         187                            5 
              Hispanoamérica                        Ibiza 
                          72                          105 
                    Imperial                    Jerónimos 
                          89                           90 
                    Justicia                       La Paz 
                         785                           16 
                     Legazpi                        Lista 
                          37                          129 
                 Los Angeles                  Los Rosales 
                          16                           28 
                      Lucero                   Marroquina 
                          62                           12 
                 Media Legua                   Mirasierra 
                          17                           18 
                    Moscardó                   Niño Jesús 
                          34                           26 
                Nueva España                     Numancia 
                          60                           58 
                      Opañel                    Orcasitas 
                          57                            2 
                     Orcasur                     Pacífico 
                           8                          138 
                     Palacio                      Palomas 
                        1083                           12 
             Palomeras Bajas            Palomeras Sureste 
                          33                           15 
             Palos de Moguer                      Pavones 
                         262                            4 
                  Peñagrande                        Pilar 
                          39                           26 
               Pinar del Rey                      Piovera 
                          47                           12 
                    Portazgo                   Pradolongo 
                          19                           14 
                 Prosperidad                 Pueblo Nuevo 
                          98                           41 
               Puerta Bonita             Puerta del Angel 
                          38                          199 
                    Quintana                    Recoletos 
                          45                          172 
                       Rejas                   Rios Rosas 
                          20                          104 
                       Rosas                     Salvador 
                           4                           13 
                  San Andrés                San Cristobal 
                          21                            8 
                   San Diego                   San Fermín 
                          80                           32 
                  San Isidro            San Juan Bautista 
                          85                           26 
                 San Pascual                Santa Eugenia 
                          18                            4 
                    Simancas                          Sol 
                          45                          940 
                       Timón                    Trafalgar 
                          16                          315 
                 Universidad                Valdeacederas 
                        1358                           48 
                Valdefuentes                   Valdemarín 
                          55                            4 
                  Valdezarza                 Vallehermoso 
                          20                           60 
                    Valverde                       Ventas 
                          45                           78 
                   Vinateros                 Vista Alegre 
                          17                           74 
                       Zofío 
                           9 </code></pre>
</div>
</div>
<p>¿Cuales son los 5 barrios que tienen mayor número entradas?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># top 5 codigos postales y sus numeros de entradas</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>top_5_barrios <span class="ot">&lt;-</span> <span class="fu">sort</span>(tabla_barrios, <span class="at">decreasing =</span> <span class="cn">TRUE</span>)[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>top_5_barrios</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Embajadores Universidad     Palacio         Sol    Justicia 
       1844        1358        1083         940         785 </code></pre>
</div>
</div>
<p>¿Cuantos Tipos de Alquiler diferentes hay? ¿Cuales son? ¿Cuantas entradas en el dataframe hay por cada tipo?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>tabla_tipos_alquiler <span class="ot">&lt;-</span> <span class="fu">table</span>(<span class="fu">droplevels</span>(airbnb<span class="sc">$</span>TipoAlquiler))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>PD: Numero de tipos de alquiler en el dataset:</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(tabla_tipos_alquiler)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>PD: Cuales son los Tipos de barrio y cuantas entradas tienen:</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>tabla_tipos_alquiler</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Entire home/apt    Private room     Shared room 
           7903            5113             191 </code></pre>
</div>
</div>
<p>Muestra el diagrama de cajas del precio para cada uno de los diferentes Tipos de Alquiler</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>airbnb,<span class="fu">aes</span>(<span class="at">x=</span>TipoAlquiler, <span class="at">y=</span>Precio,<span class="at">color=</span>TipoAlquiler))<span class="sc">+</span><span class="fu">geom_boxplot</span>()<span class="sc">+</span><span class="fu">scale_color_discrete</span>(<span class="at">name=</span><span class="st">"Precio"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 9 rows containing non-finite values (`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="practica_estadistica_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Cual es el precio medio de alquiler de cada uno, la diferencia que hay ¿es estadísticamente significativa? ¿Con que test lo comprobarías?</p>
<blockquote class="blockquote">
<p>PD: Precio medio segun el tipo de alquiler:</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aggregate</span>(Precio <span class="sc">~</span> TipoAlquiler, <span class="at">data =</span> airbnb, <span class="at">FUN =</span> mean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     TipoAlquiler   Precio
1 Entire home/apt 87.29661
2    Private room 34.25514
3     Shared room 29.85340</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>PD: Antes de responder a las preguntas vamos a comprobar si los diferentes grupos siguen una distribucion gaussiana para ello vamos a realizar el test de saphiro a cada uno de los grupos</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (v <span class="cf">in</span> <span class="fu">levels</span>(airbnb<span class="sc">$</span>TipoAlquiler)){</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  datos <span class="ot">&lt;-</span> airbnb<span class="sc">$</span>Precio[airbnb<span class="sc">$</span>TipoAlquiler<span class="sc">==</span>v]</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="fu">length</span>(datos) <span class="sc">&gt;</span> <span class="dv">5000</span>){</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>    datos <span class="ot">&lt;-</span> <span class="fu">sample</span>(datos, <span class="dv">5000</span>)</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Tipo de alquiler:"</span>, v,<span class="st">" pvalue:"</span>, <span class="fu">shapiro.test</span>(datos)<span class="sc">$</span>p.value))</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Tipo de alquiler: Entire home/apt  pvalue: 3.56340416799972e-72"
[1] "Tipo de alquiler: Private room  pvalue: 1.29906895397011e-84"
[1] "Tipo de alquiler: Shared room  pvalue: 4.51672121600842e-24"</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>PD:Al ser todos los pvalue menores que 0.05 podemos rechazar la hipotesis nula, es decir las distribuciones no son normales. Como los datos no siguen una distribucion normal utilizamos el test kruskal-Wallis</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kruskal.test</span>(Precio <span class="sc">~</span> TipoAlquiler, <span class="at">data =</span> airbnb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  Precio by TipoAlquiler
Kruskal-Wallis chi-squared = 7235.6, df = 2, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>PD:Como el pvalue es muy pequeno podemos indicar que hay diferencias estadisticamentes significaticas en las medianas entre al menos uno de los grupos .</p>
</blockquote>
<p>Filtra el dataframe cuyos tipo de alquiler sea ‘Entire home/apt’ y guardalo en un dataframe llamado <em>airbnb_entire</em>. Estas serán las entradas que tienen un alquiler del piso completo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>airbnb_entire <span class="ot">&lt;-</span> airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>TipoAlquiler <span class="sc">==</span> <span class="st">'Entire home/apt'</span>),]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>¿Cuales son los 5 barrios que tienen un mayor número de apartamentos enteros en alquiler? Nota: Mirar solo en airbnb_entire. A partir de este punto y hasta que se diga lo contrario partiremos de airbnb_entire.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>tabla_barrios_ent <span class="ot">&lt;-</span> <span class="fu">table</span>(<span class="fu">droplevels</span>(airbnb_entire<span class="sc">$</span>Barrio))</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>top_5_barrios_ent <span class="ot">&lt;-</span> <span class="fu">sort</span>(tabla_barrios_ent, <span class="at">decreasing =</span> <span class="cn">TRUE</span>)[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>PD:Top 5 barrios con mayor numero de apartamentos enteros en alquiler</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>top_5_barrios_ent</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Embajadores Universidad     Palacio         Sol      Cortes 
       1228         984         769         701         574 </code></pre>
</div>
</div>
<p>¿Cuales son los 5 barrios que tienen un mayor precio medio de alquiler para apartamentos enteros (es decir, del dataframe airbnb_entire)? ¿Cual es su precio medio?</p>
<p>Ayuda: Usa la función aggregate <code>aggregate(.~colname,df,mean,na.rm=TRUE)</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>precio_barrio <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(Precio <span class="sc">~</span> Barrio, <span class="at">data =</span> airbnb_entire, <span class="at">FUN =</span> mean)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>top_5_precio_barrio <span class="ot">&lt;-</span> <span class="fu">head</span>(precio_barrio[<span class="fu">order</span>(<span class="sc">-</span>precio_barrio<span class="sc">$</span>Precio),], <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>PD: Top 5 barrios con mayor precio medio de alquiler para apartamentos enteros en alquiler:</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>top_5_precio_barrio</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Barrio   Precio
77       Palomas 309.7500
50 Fuentelareina 180.0000
93     Recoletos 161.9254
43    El Plantío 150.0000
30    Castellana 141.3889</code></pre>
</div>
</div>
<p>¿Cuantos apartamentos hay en cada uno de esos barrios?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">subset</span>(tabla_barrios_ent, <span class="fu">names</span>(tabla_barrios_ent) <span class="sc">%in%</span> top_5_precio_barrio<span class="sc">$</span>Barrio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   Castellana    El Plantío Fuentelareina       Palomas     Recoletos 
           73             1             2             4           135 </code></pre>
</div>
</div>
<p>Mostrar una dataframe con el nombre del barrio, el precio y el número de entradas.</p>
<p>Ayuda: Podeis crear un nuevo dataframe con las columnas “Barrio” y “Freq” que contenga el número de entradas en cada barrio y hacer un merge con el dataframe del punto anterior.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>df_barrios_ent <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(tabla_barrios_ent)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(df_barrios_ent) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Barrio"</span>, <span class="st">"Num_Entradas"</span>)</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>Barrio_ent_precio <span class="ot">&lt;-</span> <span class="fu">merge</span>(df_barrios_ent, precio_barrio, <span class="at">by =</span> <span class="st">"Barrio"</span>)</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>Barrio_ent_precio</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          Barrio Num_Entradas    Precio
1                       Abrantes            3  46.00000
2                        Acacias           61  68.16393
3                        Adelfas           33  68.72727
4                     Aeropuerto            2  38.00000
5                        Aguilas            2  54.50000
6               Alameda de Osuna            4 138.75000
7                        Almagro           97 109.18557
8                       Almenara           25  65.68000
9                    Almendrales           18  77.50000
10                        Aluche            9  55.88889
11                        Ambroz            2  34.50000
12              Apostol Santiago            5  96.60000
13                      Arapiles           98  69.62245
14                       Aravaca            9  66.33333
15                         Arcos            4 100.50000
16                     Argüelles          143  89.57343
17                        Atocha            9  71.44444
18                 Bellas Vistas           45  51.77778
19                    Berruguete           35  53.85714
20                    Buenavista           12  57.91667
21                      Butarque            1  42.00000
22                    Campamento            9  45.55556
23                      Canillas           15 105.80000
24                    Canillejas            3  91.66667
25                      Cármenes            8  78.00000
26                 Casa de Campo           41  98.85366
27    Casco Histórico de Barajas            8 141.25000
28   Casco Histórico de Vallecas           18  61.11111
29  Casco Histórico de Vicálvaro            8  73.87500
30                    Castellana           73 141.38889
31                      Castilla           21  68.66667
32                   Castillejos           44  88.70455
33                       Chopera           34  55.02941
34                 Ciudad Jardín           32  87.62500
35          Ciudad Universitaria           13 138.30769
36                        Colina            7  64.42857
37                      Comillas           21  56.66667
38                    Concepción           16  61.93750
39                        Cortes          574  94.39373
40                   Costillares           13  95.07692
41                Cuatro Caminos           72  76.65278
42                      Delicias           51  66.00000
43                    El Plantío            1 150.00000
44                       El Viso           24  76.37500
45                   Embajadores         1228  73.70497
46                     Entrevías            4  56.25000
47                      Estrella            3  92.66667
48                     Fontarrón            5  51.80000
49              Fuente del Berro           38  70.31579
50                 Fuentelareina            2 180.00000
51                    Gaztambide           61  86.68852
52                          Goya          142 111.33803
53                    Guindalera           82  76.98780
54                        Hellín            1  42.00000
55                Hispanoamérica           52 104.44231
56                         Ibiza           64 102.62500
57                      Imperial           42  61.42857
58                     Jerónimos           62 131.82258
59                      Justicia          534  98.25468
60                        La Paz            3  65.33333
61                       Legazpi           14  79.28571
62                         Lista           72  90.11111
63                   Los Angeles            5  69.40000
64                   Los Rosales            2  75.00000
65                        Lucero           13  68.30769
66                    Marroquina            2  50.00000
67                   Media Legua           10  72.10000
68                    Mirasierra            7 101.28571
69                      Moscardó           18  56.05556
70                    Niño Jesús           15  89.23077
71                  Nueva España           42 127.30952
72                      Numancia           34  60.58824
73                        Opañel           10  51.60000
74                       Orcasur            1  45.00000
75                      Pacífico           62  89.72581
76                       Palacio          769  93.30599
77                       Palomas            4 309.75000
78               Palomeras Bajas           10  61.10000
79             Palomeras Sureste            4  31.50000
80               Palos de Moguer          135  73.31852
81                       Pavones            1  48.00000
82                    Peñagrande           11 127.63636
83                         Pilar           10  62.50000
84                 Pinar del Rey            9  79.88889
85                       Piovera            3  85.00000
86                      Portazgo            1  55.00000
87                    Pradolongo            3  61.33333
88                   Prosperidad           49  79.46939
89                  Pueblo Nuevo           13  67.46154
90                 Puerta Bonita           14  88.00000
91              Puerta del Angel           77  59.67532
92                      Quintana           17  65.00000
93                     Recoletos          135 161.92537
94                         Rejas           11  64.18182
95                    Rios Rosas           60  83.00000
96                      Salvador            5  66.40000
97                    San Andrés           12  50.91667
98                 San Cristobal            2  56.50000
99                     San Diego           32  44.34375
100                   San Fermín            8  63.50000
101                   San Isidro           39  76.10256
102            San Juan Bautista           13  75.53846
103                  San Pascual            7  72.42857
104                Santa Eugenia            2  47.00000
105                     Simancas           21  57.14286
106                          Sol          701 100.75036
107                        Timón            5  72.20000
108                    Trafalgar          223  98.57848
109                  Universidad          984  79.39674
110                Valdeacederas           25  67.36000
111                 Valdefuentes           24  84.25000
112                   Valdemarín            2  70.50000
113                   Valdezarza            3  53.33333
114                 Vallehermoso           33  92.39394
115                     Valverde           19  71.57895
116                       Ventas           26  50.03846
117                    Vinateros            2 102.50000
118                 Vista Alegre           22  59.45455
119                        Zofío            4  48.00000</code></pre>
</div>
</div>
<p>Partiendo del dataframe anterior, muestra los 5 barrios con mayor precio, pero que tengan más de 100 entradas de alquiler.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Filtramos los barrios con mas de 100 entradas</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>Barrio_100ent_precio <span class="ot">&lt;-</span> <span class="fu">subset</span>(Barrio_ent_precio, Num_Entradas <span class="sc">&gt;</span> <span class="dv">100</span>)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>top_5_Barrio_100ent_precio <span class="ot">&lt;-</span> <span class="fu">head</span>(Barrio_100ent_precio[<span class="fu">order</span>(<span class="sc">-</span>Barrio_100ent_precio<span class="sc">$</span>Precio),], <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>PD: Top 5 barrios con mayor precio medio de alquiler para apartamentos con mas de 100 entradas”)</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>top_5_Barrio_100ent_precio</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Barrio Num_Entradas    Precio
93  Recoletos          135 161.92537
52       Goya          142 111.33803
106       Sol          701 100.75036
108 Trafalgar          223  98.57848
59   Justicia          534  98.25468</code></pre>
</div>
</div>
<p>Dibuja el diagrama de densidad de distribución de los diferentes precios. Serían 5 gráficas, una por cada barrio.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (v <span class="cf">in</span> <span class="fu">droplevels</span>(top_5_Barrio_100ent_precio<span class="sc">$</span>Barrio)){</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  filtro_barrio <span class="ot">&lt;-</span> <span class="fu">subset</span>(airbnb_entire, Barrio <span class="sc">==</span> v)</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">ggplot</span>(<span class="at">data=</span>filtro_barrio) <span class="sc">+</span> <span class="fu">aes</span>(<span class="at">x =</span> Precio) <span class="sc">+</span> <span class="fu">geom_density</span>() <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> v ))</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 rows containing non-finite values (`stat_density()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="practica_estadistica_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="practica_estadistica_files/figure-html/unnamed-chunk-41-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="practica_estadistica_files/figure-html/unnamed-chunk-41-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="practica_estadistica_files/figure-html/unnamed-chunk-41-4.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="practica_estadistica_files/figure-html/unnamed-chunk-41-5.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Calcula el tamaño medio, en metros cuadrados, para los 5 barrios anteriores y muestralo en el mismo dataframe junto con el precio y número de entradas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Aniadimos nueva columna</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>top_5_Barrio_100ent_precio<span class="sc">$</span>MetrosCuadrados <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (v <span class="cf">in</span> <span class="fu">droplevels</span>(top_5_Barrio_100ent_precio<span class="sc">$</span>Barrio)){</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>  filtro_barrio <span class="ot">&lt;-</span> <span class="fu">subset</span>(airbnb_entire, Barrio <span class="sc">==</span> v)</span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>  m2_barrio <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(MetrosCuadrados <span class="sc">~</span> Barrio, <span class="at">data =</span> filtro_barrio, <span class="at">FUN =</span> mean)</span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>  top_5_Barrio_100ent_precio<span class="sc">$</span>MetrosCuadrados[top_5_Barrio_100ent_precio<span class="sc">$</span>Barrio <span class="sc">==</span> v] <span class="ot">&lt;-</span> m2_barrio<span class="sc">$</span>MetrosCuadrados</span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>PD: Se anade al dataframe la columna con la media de los metros cuadrados</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>top_5_Barrio_100ent_precio</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Barrio Num_Entradas    Precio MetrosCuadrados
93  Recoletos          135 161.92537        26.66316
52       Goya          142 111.33803        51.68504
106       Sol          701 100.75036        45.61692
108 Trafalgar          223  98.57848        29.30426
59   Justicia          534  98.25468        28.52669</code></pre>
</div>
</div>
<p>Dibuja el diagrama de densidad de distribución de los diferentes tamaños de apartamentos. Serían 5 gráficas, una por cada barrio.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (v <span class="cf">in</span> <span class="fu">droplevels</span>(top_5_Barrio_100ent_precio<span class="sc">$</span>Barrio)){</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  filtro_barrio <span class="ot">&lt;-</span> <span class="fu">subset</span>(airbnb_entire, Barrio <span class="sc">==</span> v)</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">ggplot</span>(<span class="at">data=</span>filtro_barrio,<span class="fu">aes</span>(<span class="at">x =</span> MetrosCuadrados))  <span class="sc">+</span> <span class="fu">geom_density</span>() <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> v ))</span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 132 rows containing non-finite values (`stat_density()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="practica_estadistica_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 139 rows containing non-finite values (`stat_density()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="practica_estadistica_files/figure-html/unnamed-chunk-44-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 641 rows containing non-finite values (`stat_density()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="practica_estadistica_files/figure-html/unnamed-chunk-44-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 216 rows containing non-finite values (`stat_density()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="practica_estadistica_files/figure-html/unnamed-chunk-44-4.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 517 rows containing non-finite values (`stat_density()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="practica_estadistica_files/figure-html/unnamed-chunk-44-5.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Esta claro que las medias de metros cuadrados de cada uno de estos 5 barrios parecen ser diferentes, pero ¿son estadísticamente diferentes? ¿Que test habría que usar para comprobarlo?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co">#creamos un dataset solo con los barrios que nos interesan</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>airbnv_entire_top5 <span class="ot">&lt;-</span> <span class="fu">subset</span>(airbnb_entire, Barrio <span class="sc">%in%</span> <span class="fu">droplevels</span>(top_5_Barrio_100ent_precio<span class="sc">$</span>Barrio))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>PD:Ya que a simple vista de los graficos de densidad antes calculados se observa que la media no sigue una distribucion gausiana. Por lo que vamos a usar el test de kruskal-wallis</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kruskal.test</span>(MetrosCuadrados<span class="sc">~</span>Barrio, <span class="at">data=</span>airbnv_entire_top5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  MetrosCuadrados by Barrio
Kruskal-Wallis chi-squared = 1.882, df = 4, p-value = 0.7574</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>PD:Al salir el test de Kruskal-wallis un p-value mayor que 0.05 no podemos descartar la hipotesis nula de que las medias son iguales. Por lo que e stadisticamente hablando no podemos decir que son diferentes.</p>
</blockquote>
<p>Para únicamente los pisos de alquiler en el barrio de Sol:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>barrio_sol<span class="ot">&lt;-</span><span class="fu">subset</span>(airbnb_entire,Barrio<span class="sc">==</span><span class="st">"Sol"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Calcular un modelo lineal que combine alguna de estas variables: * NumBanyos * NumDormitorios * MaxOcupantes * MetrosCuadrados</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co">#calculamos el modelo lineal entre numero de dormitorios y maximos ocupantes</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>barrio_sol, <span class="at">formula=</span> MaxOcupantes <span class="sc">~</span> NumDormitorios)</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = MaxOcupantes ~ NumDormitorios, data = barrio_sol)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.6052 -0.9541  0.0459  0.4955  7.3948 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     2.40373    0.08842   27.19   &lt;2e-16 ***
NumDormitorios  1.55038    0.05023   30.86   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.339 on 699 degrees of freedom
Multiple R-squared:  0.5768,    Adjusted R-squared:  0.5762 
F-statistic: 952.6 on 1 and 699 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Pintamos los datos y el modelo</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Agregar las predicciones del modelo al conjunto de datos original</span></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>barrio_sol<span class="sc">$</span>predicciones <span class="ot">&lt;-</span> <span class="fu">predict</span>(model)</span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Graficar los puntos y la línea usando ggplot2</span></span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(barrio_sol, <span class="fu">aes</span>(<span class="at">x =</span> NumDormitorios, <span class="at">y =</span> MaxOcupantes)) <span class="sc">+</span></span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span>  <span class="co"># Agregar puntos</span></span>
<span id="cb77-8"><a href="#cb77-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> predicciones), <span class="at">color =</span> <span class="st">"blue"</span>)  <span class="co"># Agregar línea</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="practica_estadistica_files/figure-html/unnamed-chunk-49-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Primero calculamos la correlación para ver como se relacionan estas variables entre sí.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(barrio_sol[,<span class="fu">c</span>(<span class="st">"NumBanyos"</span>, <span class="st">"NumDormitorios"</span>, <span class="st">"MaxOcupantes"</span>, <span class="st">"MetrosCuadrados"</span>)],<span class="at">use=</span><span class="st">"pairwise.complete.obs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                NumBanyos NumDormitorios MaxOcupantes MetrosCuadrados
NumBanyos       1.0000000      0.6761906    0.6578162       0.4820549
NumDormitorios  0.6761906      1.0000000    0.7594598       0.5684521
MaxOcupantes    0.6578162      0.7594598    1.0000000       0.4286233
MetrosCuadrados 0.4820549      0.5684521    0.4286233       1.0000000</code></pre>
</div>
</div>
<p>Se observa que la correlación entre el número de dormitorios y los metros cuadrados es sorprendentemente baja. ¿Son de fiar esos números?</p>
<blockquote class="blockquote">
<p>PD: En el dataset se observa que hay muchos apartamentos con metros cuadrados igual a 0 cosa que es imposible por lo que no son fiables esos datos</p>
</blockquote>
<p>Mediante un histograma o curvas de densidad podemos descartar números que notienen sentido en el dataframe barrio_sol, para tener una matriz de correlación que tenga mayor sentido.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">c</span>(<span class="st">"NumBanyos"</span>,<span class="st">"NumDormitorios"</span>,<span class="st">"MaxOcupantes"</span>, <span class="st">"MetrosCuadrados"</span>)){</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">ggplot</span>(<span class="at">data=</span>barrio_sol, <span class="fu">aes</span>(<span class="at">x=</span> .data[[i]]))<span class="sc">+</span> <span class="fu">geom_histogram</span>() <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> i ))</span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="practica_estadistica_files/figure-html/unnamed-chunk-51-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="practica_estadistica_files/figure-html/unnamed-chunk-51-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="practica_estadistica_files/figure-html/unnamed-chunk-51-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 641 rows containing non-finite values (`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="practica_estadistica_files/figure-html/unnamed-chunk-51-4.png" class="img-fluid" width="672"></p>
</div>
</div>
<blockquote class="blockquote">
<p>PD:De los histogramas deducimos lo siguiente: NumBanyos la gran mayoria de los apartamentos tienen 1 banyo. NumDormitorios hay muchos apartamentos que tienen 0 dormitorios, no podemos descartar estos valores. MaxOcupantes no se observa nada en especial salvo que la gran mayoria de apartamentos tienen una max ocupacion de 4. MetrosCuadrados, se observa que hay muchos datos con 0 metros cuadrados con un valor de 0 cosa que no es posible.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Pasamos a limpiar estos valores</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>limpieza_sol_1 <span class="ot">&lt;-</span> <span class="fu">which</span>((barrio_sol<span class="sc">$</span>MetrosCuadrados <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">'0'</span>)) )</span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>barrio_sol[limpieza_sol_1,<span class="st">'MetrosCuadrados'</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Una vez que hayamos filtrado los datos correspondientes calcular el valor o la combinación de valores que mejor nos permite obtener el precio de un inmueble. ¿Que variable es más fiable para conocer el precio de un inmueble, el número de habitaciones o los metros cuadrados?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Primero obtenemos la correlaciones entre variables</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(barrio_sol[,<span class="fu">c</span>(<span class="st">"Precio"</span>,<span class="st">"NumBanyos"</span>, <span class="st">"NumDormitorios"</span>, <span class="st">"MaxOcupantes"</span>, <span class="st">"MetrosCuadrados"</span>)],<span class="at">use=</span><span class="st">"pairwise.complete.obs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   Precio NumBanyos NumDormitorios MaxOcupantes MetrosCuadrados
Precio          1.0000000 0.6474419      0.6542553    0.6578409       0.7402007
NumBanyos       0.6474419 1.0000000      0.6761906    0.6578162       0.5712130
NumDormitorios  0.6542553 0.6761906      1.0000000    0.7594598       0.7717458
MaxOcupantes    0.6578409 0.6578162      0.7594598    1.0000000       0.7108265
MetrosCuadrados 0.7402007 0.5712130      0.7717458    0.7108265       1.0000000</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>PD: Obtenemos la mejor correlacion entre el precio y los metros cuadrados por lo que la consideramos la mas fiables y calcularemos un modelo del precio segun esta variable</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>model_pre_m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>barrio_sol, <span class="at">formula=</span> Precio <span class="sc">~</span> MetrosCuadrados)</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_pre_m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Precio ~ MetrosCuadrados, data = barrio_sol)

Residuals:
    Min      1Q  Median      3Q     Max 
-61.175 -21.635  -6.466  20.533 128.270 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      46.5709    10.3852   4.484 6.55e-05 ***
MetrosCuadrados   0.8342     0.1229   6.786 4.80e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 38.53 on 38 degrees of freedom
  (661 observations deleted due to missingness)
Multiple R-squared:  0.5479,    Adjusted R-squared:  0.536 
F-statistic: 46.05 on 1 and 38 DF,  p-value: 4.795e-08</code></pre>
</div>
</div>
<p>Responde con su correspondiente margen de error del 95%, ¿cuantos euros incrementa el precio del alquiler por cada metro cuadrado extra del piso?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model_pre_m2, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     2.5 %    97.5 %
(Intercept)     25.5471054 67.594737
MetrosCuadrados  0.5853331  1.083027</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>PD: El incremento de precio por metro cuadrado es 0.8342 euros/m2 con un intervalo de confianza del 95% de [0.5853331,1.083027]euros/m2</p>
</blockquote>
<p>Responde con su correspondiente margen de error del 95%, ¿cuantos euros incrementa el precio del alquiler por cada habitación?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a> <span class="co">#modelo del precio segun habitacion</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>model_pre_dor <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>barrio_sol, <span class="at">formula=</span> Precio <span class="sc">~</span> NumDormitorios)</span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_pre_dor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Precio ~ NumDormitorios, data = barrio_sol)

Residuals:
     Min       1Q   Median       3Q      Max 
-206.225  -22.676   -4.312   16.416  263.960 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      52.584      2.568   20.48   &lt;2e-16 ***
NumDormitorios   33.364      1.459   22.87   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 38.9 on 699 degrees of freedom
Multiple R-squared:  0.4281,    Adjusted R-squared:  0.4272 
F-statistic: 523.1 on 1 and 699 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model_pre_dor, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  2.5 %   97.5 %
(Intercept)    47.54299 57.62561
NumDormitorios 30.50004 36.22803</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>PD: El incremento de precio por numero de dormitorios es de 33.368 euros/habitacion con un intervalo de confianza del 95% de [30.50004,36.22803]euros/m2</p>
</blockquote>
<p>¿Cual es la probabilidad de encontrar, en el barrio de Sol, un apartamento en alquiler con 3 dormitorios? ¿Cual es el intervalo de confianza de esa probabilidad?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>Num_apar_sol <span class="ot">&lt;-</span> <span class="fu">nrow</span>(barrio_sol)</span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a>Num_apar_3hab <span class="ot">&lt;-</span> <span class="fu">nrow</span>(<span class="fu">subset</span>(barrio_sol, NumDormitorios <span class="sc">==</span> <span class="dv">3</span>))</span>
<span id="cb97-4"><a href="#cb97-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-5"><a href="#cb97-5" aria-hidden="true" tabindex="-1"></a>Probabilidad_3hab <span class="ot">&lt;-</span> Num_apar_3hab<span class="sc">/</span>Num_apar_sol</span>
<span id="cb97-6"><a href="#cb97-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-7"><a href="#cb97-7" aria-hidden="true" tabindex="-1"></a><span class="fu">binom.test</span>(Num_apar_3hab,Num_apar_sol,Probabilidad_3hab)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Exact binomial test

data:  Num_apar_3hab and Num_apar_sol
number of successes = 55, number of trials = 701, p-value = 1
alternative hypothesis: true probability of success is not equal to 0.07845934
95 percent confidence interval:
 0.0596506 0.1009033
sample estimates:
probability of success 
            0.07845934 </code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>PD: La probabilidad de econtrar un apartamento de 3 habitaciones es de 7.85% con un intervalo de confianza del 95% para valores entre [5.96,10.09]%</p>
</blockquote>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>